package com.joseluis.pe.cpresentacion;

import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author jeybi
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        btnMenuCalculadora = new javax.swing.JMenuItem();
        btnMenuContador = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        btnTipoDocumento = new javax.swing.JMenu();
        btnMenuTipoDocumento = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        btnMenuPersonaDocumento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        principal.setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );

        jMenuBar2.setFocusCycleRoot(true);
        jMenuBar2.setOpaque(true);

        jMenu3.setText("Aplicaciones");

        btnMenuCalculadora.setText("Calculadora");
        btnMenuCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuCalculadoraActionPerformed(evt);
            }
        });
        jMenu3.add(btnMenuCalculadora);

        btnMenuContador.setText("Contador");
        btnMenuContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuContadorActionPerformed(evt);
            }
        });
        jMenu3.add(btnMenuContador);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        btnTipoDocumento.setText("Mantenimiento");

        btnMenuTipoDocumento.setText("Tipo Documento");
        btnMenuTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuTipoDocumentoActionPerformed(evt);
            }
        });
        btnTipoDocumento.add(btnMenuTipoDocumento);

        jMenuItem2.setText("Persona");
        btnTipoDocumento.add(jMenuItem2);

        btnMenuPersonaDocumento.setText("Persona Documento");
        btnMenuPersonaDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPersonaDocumentoActionPerformed(evt);
            }
        });
        btnTipoDocumento.add(btnMenuPersonaDocumento);

        jMenuBar2.add(btnTipoDocumento);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuCalculadoraActionPerformed
        //Para pintar un JPanel
        Calculadora cal = new Calculadora();
        cal.setSize(419, 599);
        cal.setLocation(0,0);
        principal.removeAll();
        principal.add(cal, BorderLayout.CENTER);
        principal.revalidate();
        principal.repaint();
    }//GEN-LAST:event_btnMenuCalculadoraActionPerformed

    private void btnMenuContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuContadorActionPerformed
        Contador con = new Contador();
        con.setSize(500, 600);
        con.setLocation(0,0);
        principal.removeAll();
        principal.add(con, BorderLayout.CENTER);
        principal.revalidate();
        principal.repaint();
    }//GEN-LAST:event_btnMenuContadorActionPerformed

    private void btnMenuTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuTipoDocumentoActionPerformed
        try {
            jpTipoDocumento tp = new jpTipoDocumento();
            tp.setSize(617, 408);
            tp.setLocation(0,0);
            principal.removeAll();
            principal.add(tp, BorderLayout.CENTER);
            principal.revalidate();
            principal.repaint();
        } catch (SQLException ex) {
            Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMenuTipoDocumentoActionPerformed

    private void btnMenuPersonaDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPersonaDocumentoActionPerformed
       
            jpPersonadocumento pd = new jpPersonadocumento();
            pd.setSize(617,408);
            pd.setLocation(0,0);
            principal.removeAll();
            principal.add(pd, BorderLayout.CENTER);
            principal.revalidate();
            principal.repaint();
        
    }//GEN-LAST:event_btnMenuPersonaDocumentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnMenuCalculadora;
    private javax.swing.JMenuItem btnMenuContador;
    private javax.swing.JMenuItem btnMenuPersonaDocumento;
    private javax.swing.JMenuItem btnMenuTipoDocumento;
    private javax.swing.JMenu btnTipoDocumento;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel principal;
    // End of variables declaration//GEN-END:variables
}
